# Generated by Django 3.0.6 on 2020-05-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_repairs', models.DateField(auto_now=True)),
                ('address', models.CharField(max_length=250)),
                ('total', models.IntegerField()),
            ],
            options={
                'ordering': ('-date_repairs',),
            },
        ),
    ]
